name: HAC v2 Forecast & Validation

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # allows manual run
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  hac-forecast:
    runs-on: ubuntu-latest
    env:
      TZ: UTC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install HAC v2 dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Dependências específicas HAC v2
          pip install cdasws tensorflow torch prophet
          pip install statsmodels

      - name: Create results dirs
        run: |
          mkdir -p data results plots logs models

      - name: Coletar dados OMNI históricos
        run: |
          python src/data_fetcher_omni.py

      - name: Coletar dados NOAA tempo real
        run: |
          python src/data_fetcher.py

      - name: Rodar validação HAC v2
        run: |
          python src/hac_validation.py

      - name: Analisar impactos classe X
        run: |
          python src/impact_predictor.py

      - name: Add and commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/* plots/* logs/* data/*.csv || true
          git commit -m "🚀 HAC v2: Validação científica completa + Dados OMNI $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nada a commitar"
          git push origin HEAD:main || echo "Push falhou — verifique permissões"

      - name: Upload HAC v2 results artifact
        uses: actions/upload-artifact@v4
        with:
          name: hac-v2-validation-results
          path: |
            results/**
            plots/**
            logs/**
            data/*.csv
