name: HAC Forecast & Validation

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # allows manual run
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  hac-forecast:
    runs-on: ubuntu-latest
    env:
      TZ: UTC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Instalações específicas para análise de impactos
          pip install scikit-learn sunpy

      - name: Create results dirs
        run: |
          mkdir -p data results plots logs

      - name: Coletar dados NOAA (data_fetcher.py)
        run: |
          python src/data_fetcher.py

      - name: Rodar validação HAC (hac_validation.py)
        run: |
          python src/hac_validation.py

      - name: Analisar impactos classe X (impact_predictor.py)
        run: |
          python src/impact_predictor.py

      - name: Add and commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/* plots/* logs/* data/solar_data_latest.csv || true
          git commit -m "🚨 Atualização automática: Previsões HAC + Alertas Classe X $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nada a commitar"
          git push origin HEAD:main || echo "Push falhou — verifique permissões"

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: hac-validation-results
          path: |
            results/**
            plots/**
            logs/**
            data/solar_data_latest.csv
